version: "3.7"
services:
  node-express-docker:
    build: .
    volumes:
      - .:/usr/app
    container_name: node-express-docker
    expose:
      - "3030"
    ports:
      - "3030:3030"
    command: sh -c "npm install && npm start"
